const RequestQuestion = (slug ,title, content, status, author, quiz ,correct_message, incorrect_message, hints_enabled, hints_message, points ,points_per_answer, question_type, answer_sets) => {
    const template = {
      "date": "2023-02-15T12:00:00",
      "date_gmt": "2023-02-15T17:00:00", 
      "guid": "",
      "link": "",
      "modified": "2023-02-16T09:30:00",
      "modified_gmt": "2023-02-16T14:30:00",
      "slug": "de prueba",
      "status": "publish",
      "type": "post",
      "password": "",
      "permalink_template": "/%year%/%monthnum%/%day%/%postname%/",
      "generated_slug": "",
      "title": "de prueba",
      "content": "Contenido de la prueba",
      "author": 1,
      "featured_media": null,
      "comment_status": "open",
      "ping_status": "open",
      "menu_order": 0,
      "template": 
      "",
      "categories": [], 
      "tags": [],
      "ld_quiz_category": [],
      "ld_quiz_tag": [],
      "course": 2752,
      "lesson": 2753,
      "prerequisites": [],
      "registered_users_only": false,
      "passing_percentage": 80,
      "certificate_award_threshold": 100,
      "retry_restrictions_enabled": false, 
      "retry_repeats": "0",
      "answer_all_questions_enabled": true,
      "time_limit_enabled": false,
      "time_limit_time": 60,
      "materials_enabled": false,
      "materials": "",
      "auto_start": false,
      "quiz_modus": "single",
      "review_table_enabled": true,
      "summary_hide": false,
      "skip_question_disabled": false,
      "custom_sorting": false,
      "sort_categories": false,
      "question_random": false, 
      "show_max_question": false,
      "show_points": true,
      "show_category": false,
      "hide_question_position_overview": false,
      "hide_question_numbering": false,
      "numbered_answer": false,
      "answer_random": false,
      "title_hidden": false,
      "restart_button_hide": false,
      "show_average_result": true,
      "show_category_score": false,
      "hide_result_points": false,
      "hide_result_correct_question": false,
      "hide_result_quiz_time": false,
      "custom_answer_feedback": false,
      "hide_answer_message_box": false,
      "disabled_answer_mark": false,
      "view_question_button_hidden": false,
      "toplist_enabled": false,
      "toplist_data_add_permissions": "1",
      "toplist_data_add_multiple": false,
      "toplist_data_add_automatic": false,
      "toplist_data_show_limit": 10,
      "toplist_data_sort": "1",
      "toplist_data_showin_enabled": false,
      "statistics_enabled": false,
      "view_profile_statistics_enabled": false,
      "statistics_ip_lock_enabled": false,
      "email_enabled": false,
      "email_admin_enabled": false,
      "email_user_enabled": false,
      "certificate": null,
      "answers": {"_answerData":[{"_points":1,"_gradedType":"text","_gradingProgression":"not-graded-none","_correct":true,"_html":false,"_graded":"1","_sortString":"","_type":"answer","_sortStringHtml":false,"_answer":"Respuesta 1"},{"_points":0,"_gradedType":"text","_gradingProgression":"not-graded-none","_correct":false,"_html":false,"_graded":"1","_sortString":"","_type":"answer","_sortStringHtml":false,"_answer":"Respuesta 2"},{"_answer":"Respuesto 4","_html":false,"_points":0,"_correct":false,"_sortString":"","_sortStringHtml":false,"_graded":"1","_gradingProgression":"","_gradedType":"text","_type":"answer","_answerType":"single"},{"_answer":"Respuesta 4","_html":false,"_points":0,"_correct":false,"_sortString":"","_sortStringHtml":false,"_graded":"1","_gradingProgression":"","_gradedType":"text","_type":"answer","_answerType":"single"}]}
      
}
      
      return template;
}

export default RequestQuestion