name: WPCS checker
on: push
jobs:
  linter_name:
    name: runner / phpcs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shalior/wordpress-phpcs-action@master
        with:
          github_token: ${{ secrets.github_token }}
          use_default_configuration_file: true
          workdir: .
          phpcs_args: '.'
          phpcbf_args: '.'
          phpcs_standard: 'WordPress --extensions=php --ignore=*/vendor/*'
      - uses: stefanzweifel/git-auto-commit-action@v4 # auto commit the fixes action for GitHub
        with:
          commit_message: Fix PHPCS errors
